### ISSUE TITLE
Scala 2.10.x support

### ISSUE THREAD

**Issue by wattdave** [scalation/scalation#1]
Do you have any preliminary work on refactoring this to remove scala Actors in favor of Akka actors, so this can move to more recent Scala versions? In my fork, I've got all of the floating point number warnings fixed, and was about to have a look at the actors, but I figured I'd ask first.

**Comment by mepcotterell** [comment]
Closing. The latest version of ScalaTion is compatible with Scala 2.11. We'll begin fully hosting ScalaTion here on GitHub soon (hopefully before the end of spring semester) in order to make development more transparent and make it easier for people to use ScalaTion.
